# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = """
$cmd_duration
$nix_shell
$rust
$bun
$nodejs
$ruby
$time"""

[character]
error_symbol = "[✗](bold red)"
# success_symbol = "[✔](bold green)"
# symbol = "➜"


[fill]
symbol = "󰏗 "

[time]
disabled = false
format = "[$time]($style)"
style = "italic dimmed white"
time_format = "%T"
utc_time_offset = "local"

[cmd_duration]
format = "[⏱ $duration]($style) "
min_time = 5000

[git_status]
conflicted = "  "
deleted = " 﫧"
modified = "  "
renamed = "  "
staged = "  "
stashed = ""
untracked = "  "

[git_branch]
ignore_branches = ['main', 'master']
symbol = " "

[git_commit]
tag_symbol = '  '

[hostname]
ssh_symbol = " "

[nix_shell]
format = "[$symbol]($style) "
symbol = ""

[nodejs]
format = "[$symbol]($style) "
symbol = ""

[bun]
format = "[$symbol]($style) "
symbol = ""

[os.symbols]
Alpine = " "
Linux = " "
Macos = " "
NixOS = " "
Raspbian = " "
RockyLinux = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
disabled = true
symbol = "󰏗 "

[rust]
symbol = "󱘗 "

[ruby]
format = "[$symbol]($style)"
symbol = " "

[docker_context]
symbol = " "
