# version: 1.0.0

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[character]
error_symbol = "[○](italic purple)"
format = "$symbol "
success_symbol = "[◎](bold italic bright-yellow)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
disabled = false
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"

[username]
disabled = false
format = "[⭘ $user]($style) "
show_always = false
style_root = "purple bold italic"
style_user = "bright-yellow bold italic"

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
home_symbol = "⌂"
read_only = " ◈"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-blue)'
repo_root_style = 'bold blue'
style = "italic blue"
truncation_length = 2
truncation_symbol = "□ "
use_os_path_sep = true

[cmd_duration]
format = "[◄ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
disabled = false
format = " ◯[$localipv4](bold magenta)"
ssh_only = true

[time]
disabled = false
format = "[ $time]($style)"
style = "italic dimmed white"
time_format = "%R"
utc_time_offset = "local"

[battery]
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
empty_symbol = "▃"
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
unknown_symbol = "░"

[[battery.display]]
style = "italic bold red"
threshold = 20

[[battery.display]]
style = "italic dimmed bright-purple"
threshold = 60

[[battery.display]]
style = "italic dimmed yellow"
threshold = 70

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
ignore_branches = ["main", "master"]
only_attached = true
style = "italic bright-blue"
symbol = "[△](bold italic bright-blue)"
truncation_length = 22
truncation_symbol = "⋯"

[git_metrics]
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
disabled = false
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
ignore_submodules = true

[git_status]
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
conflicted = "[◪◦](italic bright-magenta)"
deleted = "[✕](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
modified = "[●◦](italic yellow)"
renamed = "[◎◦](italic bright-blue)"
staged = "[▪┤[$count](bold white)│](italic bright-cyan)"
stashed = ""
style = "bold italic bright-blue"
untracked = "[◌◦](italic bright-yellow)"

[memory_usage]
format = " mem [${ram}( ${swap})]($style)"
symbol = "▪▫▪ "

[nim]
format = " nim [$symbol($version )]($style)"
symbol = "▴▲▴ "

[nix_shell]
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
style = 'bold italic dimmed blue'
symbol = '✶'
unknown_msg = '[◌](bold dimmed ellow)'

[spack]
format = " spack [$symbol$environment]($style)"
symbol = "◇ "
