window:
  padding:
    x: 20
    y: 16
  dynamic_padding: true
  decorations: transparent

font:
  normal:
    family: Hack Nerd Font
  size: 15

colors:
  primary:
    background: '#111111'

mouse:
  url:
    modifiers: Command