keys:
  - &orvar "age1420l9x43gmsawwjhs6a0c63ce8udf8f8k8pjyaaqs6m3ltn9t55ssgxq3n"

creation_rules:
  - path_regex: hosts/snufkin/secrets(/[^/]+)?\.yaml$
    key_groups:
      - age:
          - *orvar
          - "age1cp2hvqljfv8clc6qge2s3eqpgxe3tar47jugcusdfqval4e8eqesq5dhsk"
