#!/usr/bin/env bash

git branch -r --merged |
  grep origin |
  grep -v '>' |
  grep -v develop |
  grep -v nightly |
  grep -v feature/calcatron |
  sed 's|  origin/||'

# git-cleanup-remote | xargs --replace=\{\} git log -n 1 --pretty=format:"%at%x09 %<(35)%aD%x09 %<(20)%an%x09 %d" origin/\{\}