#!/usr/bin/env node

const { execSync } = require('child_process')

const download = (url) => {
    return JSON.parse(rawDownload(url))
}

const rawDownload = (url) => {
    console.log('Downloading', url)
    return execSync(`curl -s -X GET --header 'Accept: application/json' '${url}'`).toString()
}

const say = (sentence) => {
    console.log(sentence)
    execSync(`say "${sentence.replace('"', '\'')}"`)
}

const options = [
    () => say(download('http://api.adviceslip.com/advice').slip.advice),
    () => say(download('https://catfact.ninja/fact').fact),
    () => say(rawDownload('https://insult.mattbas.org/api/insult')),
]

try {
    options[Math.floor(Math.random() * options.length)]()
} catch(e) {
    say('your shitty script doesn\'t work')
}
