#!/usr/bin/env node

const { execSync } = require('child_process');
const { readFileSync } = require('fs');

const files = execSync('rg --no-heading \' extends RouteConfiguration\' | cut -f1 -d:')
    .toString()
    .trim()
    .split('\n')
    .map(f => f.trim());

let totalRoutes = 0;
files.forEach(fileName => {
    const contents = readFileSync(fileName, 'utf8');
    const lines = contents.split('\n').map(l => l.trim());
    const startIndex = lines.findIndex(l => l.includes('public void setupRoutes() {'));
    const endIndex = startIndex + lines.slice(startIndex).findIndex(l => l.includes('}'));
    const relevantLines = lines.slice(startIndex + 1, endIndex).filter(l => l.length > 0);
    console.log('##### ' + fileName);
    relevantLines.forEach(l => console.log('* ' + l))
    console.log();

    totalRoutes += relevantLines.length;
});

console.log('Total routes: ' + totalRoutes);