#!/bin/bash

branchName=`git rev-parse --abbrev-ref HEAD`
referenceName=origin/$branchName
args="${@:1}"
if [ "$1" != "" ] && [[ "$1" != -* ]]
then
    referenceName=$1
    args="${@:2}"
fi
git log --no-merges $referenceName..$branchName $args
