#!/bin/bash


branchName=`git rev-parse --abbrev-ref HEAD`
referenceName=origin/$branchName
if [ "$1" != "" ]
then
    referenceName=$1
fi

git rev-list --left-right ${referenceName}...${branchName} -- 2>/dev/null >/tmp/git_upstream_status_delta || continue
LEFT_AHEAD=$(grep -c '^<' /tmp/git_upstream_status_delta)
RIGHT_AHEAD=$(grep -c '^>' /tmp/git_upstream_status_delta)
echo "branch: $referenceName"
echo "$LEFT_AHEAD ahead, $RIGHT_AHEAD behind $branchName"
