#!/bin/bash

# Usage: ./filename frequency_in_seconds folder_path

# If the script doesn't work, you may need imagemagick:
# $ sudo apt-get install imagemagick

x=1

if [[ -f ${2}/screenshot1.png ]]; then
  echo "Folder already has screenshots, pick a new one or clear the folder (rm *.png)"
  exit 1
fi

echo "Saving a screenshot in $2 every $1 seconds"
while [ true ]
do
  echo "Saving screenshot..."
  import -window root ${2}/screenshot${x}.png
  x=$(( $x + 1 ))
  sleep $1
done
